version: '3.8'

services:
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASS: ${WORDPRESS_ADMIN_PASS}
      WORDPRESS_EXTRA_USER: ${WORDPRESS_EXTRA_USER}
      WORDPRESS_EXTRA_EMAIL: ${WORDPRESS_EXTRA_EMAIL}
      WORDPRESS_EXTRA_PASS: ${WORDPRESS_EXTRA_PASS}
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - my_network
    working_dir: /var/www/html
    command: bash /setup.sh
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_DATABASE: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
  
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - my_network
    command: nginx -g "daemon off;"

networks:
  my_network:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/jsiegers/data/mariadb
      o: bind
      type: none
  wordpress_files:
    driver: local
    driver_opts:
      device: /home/jsiegers/data/wordpress
      o: bind
      type: none


#TODO: remove passwords and stuff from wp-config.php