version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
        MYSQL_PASS: ${MYSQL_PASS}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
    restart: always
    user: mysql
    environment:
      MYSQL_ROOT_PASS: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_DATABASE}
      MYSQL_DATABASE: ${MYSQL_PASS}
      MYSQL_USER: ${MYSQL_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_EXTRA_USER: ${WP_EXTRA_USER}
      WP_EXTRA_EMAIL: ${WP_EXTRA_EMAIL}
      WP_EXTRA_PASS: ${WP_EXTRA_PASS}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    working_dir: /var/www/html
    command: bash /setup.sh

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    command: nginx -g "daemon off;"
    restart: always
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception_network
    depends_on:
      - wordpress

networks:
  inception_network:


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/gpirro/data/mariadb
      o: bind
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/gpirro/data/wordpress
      o: bind
      type: none
