version: '3.8'

services:
  wordpress:
    build: ./srcs/wordpress
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_NAME: mariadb 
      WORDPRESS_DB_USER: mariadbuser 
      WORDPRESS_DB_PASSWORD: 'abc'
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_URL: jsiegers.42.fr
      WORDPRESS_TITLE: deine_muti
      WORDPRESS_ADMIN_USER: deinemuti
      WORDPRESS_ADMIN_EMAIL: deinemuti@kokos.nl
      WORDPRESS_ADMIN_PASS: 'Test123!'
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - my_network
    working_dir: /var/www/html
    # command: php-fpm7.3 -F
    command: bash /setup.sh
    # command: tail -f /dev/null


  mariadb:
    build: 
      context: ./srcs/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: 'abc'
        MYSQL_PASSWORD: 'abc'
        MYSQL_DATABASE: mariadb
        MYSQL_USER: mariadbuser
    image: mariadb
    restart: always
    user: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'abc'
      MYSQL_PASSWORD: 'abc'
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadbuser
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
  
  nginx:
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./srcs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - my_network
    command: nginx -g "daemon off;"

networks:
  my_network:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/jsiegers/data/mariadb
      o: bind
      type: none
  wordpress_files:
    driver: local
    driver_opts:
      device: /home/jsiegers/data/wordpress
      o: bind
      type: none